

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    mapper-locations: classpath*:com/sp/**/*Mapper.xml


server:
  port: 8001
  servlet:
    context-path: /sp